### ISSUE TITLE
Templatize mockups/examples

### ISSUE THREAD

**Issue by oubiwann** [lfe/docs3#11]
We need to perform the following templatization tasks:

- ~~Convert HTML to Exemplar S-expressions~~
- ~~Split S-Expressions into Modules~~
- [x] Convert HTML mockups to [Erlydtl](https://github.com/erlydtl/erlydtl) (Erlang Django Templates)
  - [x] Added erlydtl as a dep
  - [x] Create structure template with all page blocks defined
  - [x] Create base template that inherits from structure template -- this will have the page layout HTML common to all pages
  - [x] Use this base template to convert HTML mockup pages
    - [x] Convert top-nav - #5
    - ~~Convert right-nav~~ - #4
    - [x] Convert left-nav - #3
    - [x] Convert single-colume page template - #6
    - [x] Convert landing-page - #2
    - ~~Convert 2-column page~~ - #9
    - ~~Convert 3-column page~~ - #10
  - [x] Demonstrate generation of static content from erlydtl templates

This ticket is part of epic [#66](https://github.com/lfe/docs/issues/66)

**Comment by oubiwann** [comment]
Done.
